DoctorOffline/Controllers/MuluController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DoctorOffline.Entity;
using DoctorOffline.Models;
using DoctorOffline.Service;
using Microsoft.AspNetCore.Mvc;
using System.Text;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DoctorOffline.Controllers
{
    public class MuluController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            List<OnlineMulu> muluList = new OnlineMuluService().getMuluList();
            ViewData["mulus"]=muluList;
            MuluModel model = new OnlineMuluService().getMuluModelById(0);
            ViewData["html"] = GetHTML(model);
            return View(model);
        }
        public String GetHTML(MuluModel model)
        {
            StringBuilder sbHtml = new StringBuilder();
            sbHtml.Append("<li>");
            sbHtml.AppendFormat("<span id='{0}' class='folder' onclick='AddClick({0},{1},\"{2}\");'>{3}</span>",model.MuluId,model.Level,model.MuluName,model.MuluName);
            if(model.children!=null && model.children.Count > 0)
            {
                sbHtml.Append("<ul>");
                foreach (var item in model.children)
                {
                    sbHtml.Append(GetHTML(item));
                }
                sbHtml.Append("</ul>");
            }
            sbHtml.Append("</li>");
            return sbHtml.ToString();
        }
        public IActionResult AddMulu(MuluModel model){
            OnlineMulu mulu = new OnlineMulu();
            mulu.Name = model.MuluName;
            mulu.Level = model.Level;
            mulu.ParentId = model.ParentId;
            new OnlineMuluService().AddMulu(mulu);
            return this.RedirectToAction("Index");
        }

        public IActionResult MuluDetail(long muluid)
        {
            MuluModel mm=new OnlineMuluService().getMuluDetail(muluid);
            if (muluid == 0)
            {
                OnlineMulu root = new OnlineMulu();
                root.ParentId = 0;
                root.Level = 0;
                root.Name = "Root";
                mm.mulu = root;
            }
            ViewData["mm"]=mm;
            return View();
        }
        public JsonResult EditRelation(long currentMuluId,string ask120Relation,string fhRelation,string JJRelation,string JKRelation,string SJRelation)
        {
            OnlineMuluRelation relation = new OnlineMuluRelation();
            relation.OnlineMuluId = currentMuluId;
            relation.Ask120Relation = ask120Relation;
            relation.FHRelation = fhRelation;
            relation.JJRelation = JJRelation;
            relation.JKRelation = JKRelation;
            relation.SJRelation = SJRelation;
            new OnlineMuluRelationService().Save(relation);
            return Json("success");
        } 
        public JsonResult GetRelation(long onlineMulu)
        {
            RelationModel model = new RelationModel();
            var relList = new OnlineMuluRelationService().GetByOnlineMuluId(onlineMulu);
            OnlineMuluRelation rel = null;
            if(relList!=null && relList.Count > 0)
            {
                rel = relList.FirstOrDefault();
            }
            if (rel != null)
            {
                model.ask120Relation = rel.Ask120Relation;
                model.fhRelation = rel.FHRelation;
                model.JJRelation = rel.JJRelation;
                model.JKRelation = rel.JKRelation;
                model.SJRelation = rel.SJRelation;
            }else
            {
                //model.ask120Relation = "";
                //model.fhRelation = "";
                //model.JJRelation = "";
                //model.JKRelation = "";
                //model.SJRelation = "";
            }
            return Json(model);
        }
    }
}

DoctorOffline/Views/Mulu/Index.cshtml
@using DoctorOffline.Entity;
@using DoctorOffline.Models;
@model MuluModel
@{
    ViewData["Title"] = "目录列表";
    string name = ViewData["name"] == null ? "null" : ViewData["name"].ToString();
    List<OnlineMulu> ml = (List<OnlineMulu>)ViewData["mulus"];
    String html = (String)ViewData["html"];
}
<link href="~/css/jquery.treeview.css" rel="stylesheet" />
<link href="~/css/screen.css" rel="stylesheet" />
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="~/js/jquery.cookie.js"></script>
<script src="~/js/jquery.treeview.js"></script>
<script src="~/js/jquery.treeview.edit.js"></script>
<hl>目录列表:</hl>
<br />
<br />
<br />
<br />

<div style="width:300px; height:auto; float:left; display:inline">
    <ul id="tree" class="filetree">
        @Html.Raw(html)
    </ul>
    <br />
    <form asp-controller="Mulu" asp-action="AddMulu" method="post">
        <input asp-for="MuluName" />
        <input asp-for="Level" type="hidden" />
        <input asp-for="ParentId" type="hidden" />
        <button type="submit">添加</button>
    </form>
</div>
<div style="width:600px; height:auto; float:left; display:inline">

    <ul>
        <li>120ask:<input type="text" id="ask120Relation" /></li>
        <li>fh:<input type="text" id="fhRelation" /></li>
        <li>JJ:<input type="text" id="JJRelation" /></li>
        <li>JK:<input type="text" id="JKRelation" /></li>
        <li>SJ:<input type="text" id="SJRelation" /></li>
        <button onclick="saveRelation()">保存</button>
    </ul>

</div>
<input type="hidden" id="currentMuluId" />
<script type="text/javascript">
    $("#tree").treeview({ collapsed: true });
    function AddClick(muluId, level, name) {
        var iMuluId = parseInt(muluId);
        var iLevel = parseInt(level) + 1
        $("#ParentId").val(iMuluId);
        $("#Level").val(iLevel);
        $(".folder").removeClass("selectedColor");
        $("#" + muluId).addClass("selectedColor");
        $("#currentMuluId").val(iMuluId);
        initRelation(muluId);
    }
    function initRelation(currentMuluId) {
        $.ajax({
            url: "/Mulu/GetRelation",
            type: "GET",
            dataType: "json",
            data: { onlineMulu : currentMuluId},
            success: function (data) {
                $("#ask120Relation").val(data.ask120Relation);
                $("#fhRelation").val(data.fhRelation);
                $("#JJRelation").val(data.JJRelation);
                $("#JKRelation").val(data.JKRelation);
                $("#SJRelation").val(data.SJRelation);
            }
        })
    }
    function saveRelation() {
        var ask120Relation = $("#ask120Relation").val();
        var fhRelation = $("#fhRelation").val();
        var JJRelation = $("#JJRelation").val();
        var JKRelation = $("#JKRelation").val();
        var SJRelation = $("#SJRelation").val();
        var currentMuluid = $("#currentMuluId").val();
        $.ajax({
            url: "/Mulu/EditRelation",
            type: "GET",
            dataType: "json",
            data: {
                currentMuluId: currentMuluid,
                ask120Relation: ask120Relation,
                fhRelation: fhRelation,
                JJRelation: JJRelation,
                JKRelation: JKRelation,
                SJRelation: SJRelation
            },
            success: function (data) {
                alert(data);
            }
        })
    }
</script>

DoctorOffline/Views/Mulu/MuluDetail.cshtml
@using DoctorOffline.Models;
@using DoctorOffline.Models;
@model MuluModel
@{
    MuluModel mm=(MuluModel)ViewData["mm"];
    int level = mm.mulu.Level + 1;
}
<link href="~/css/jquery.treeview.css" rel="stylesheet" />
<link href="~/css/screen.css" rel="stylesheet" />
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="~/js/jquery.cookie.js"></script>
<script src="~/js/jquery.treeview.js"></script>
<script src="~/js/jquery.treeview.edit.js"></script>
<h1>@mm.mulu.Name</h1>
<ul>
    @foreach(var child in mm.children){
       <li><a href="/Mulu/MuluDetail?muluid=@child.Id">@child.Name</a></li>
     }
</ul>
<br />

<form asp-controller="Mulu" asp-action="AddMulu" method="post">
    <input asp-for="MuluName" />
    <input asp-for="Level" value="@level" type="hidden" />
    <input asp-for="ParentId" value="@mm.mulu.Id" type="hidden"/>
    <button type="submit">Register</button>
</form>
<br />
<ul id="tree" class="filetree">
    <li>
        <span class="folder">系统管理</span>
        <ul>
            <li><span class="folder">部门管理</span></li>
            <li>
                <span class="folder">岗位管理</span>
                <ul>
                    <li><span class="folder">岗位添加</span></li>
                    <li><span class="folder">岗位删除</span></li>
                </ul>
            </li>
            <li>
                <span class="folder">用户管理</span>
                <ul>
                    <li><span class="folder">添加用户</span></li>
                    <li><span class="folder">修改用户</span></li>
                </ul>
            </li>
        </ul>
    </li>
    <li><span class="folder">审批流转</span></li>
</ul>
<script type="text/javascript">
    $("#tree").treeview();
</script>